/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.coffee_mangement.view;

/**
 *
 * @author asus
 */
public class Account_Managerment extends javax.swing.JFrame {

    /**
     * Creates new form Account_Managerment
     */
    public Account_Managerment() {
        initComponents();
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNorth338 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbPosition338 = new javax.swing.JLabel();
        cbbPosition338 = new javax.swing.JComboBox<>();
        lbSearch338 = new javax.swing.JLabel();
        txtSearch338 = new javax.swing.JTextField();
        PanelSouth338 = new javax.swing.JPanel();
        btnAddAcc338 = new javax.swing.JButton();
        btnEditAcc338 = new javax.swing.JButton();
        btnDeleteAcc338 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelSouth339 = new javax.swing.JPanel();
        btnAddAcc339 = new javax.swing.JButton();
        btnEditAcc339 = new javax.swing.JButton();
        btnDeleteAcc339 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        PanelCenter338 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDish338 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");
        setBackground(new java.awt.Color(74, 211, 149));

        PanelNorth338.setBackground(new java.awt.Color(69, 32, 16));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/account.png"))); // NOI18N
        jLabel3.setText("QUẢN LÝ TÀI KHOẢN");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jLabel3.setOpaque(true);

        lbPosition338.setBackground(new java.awt.Color(255, 255, 255));
        lbPosition338.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPosition338.setForeground(new java.awt.Color(255, 255, 0));
        lbPosition338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/More-People-icon.png"))); // NOI18N
        lbPosition338.setText("Chức vụ:");

        cbbPosition338.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbPosition338.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbPosition338.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPosition338ItemStateChanged(evt);
            }
        });
        cbbPosition338.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPosition338ActionPerformed(evt);
            }
        });

        lbSearch338.setBackground(new java.awt.Color(255, 255, 255));
        lbSearch338.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearch338.setForeground(new java.awt.Color(255, 255, 0));
        lbSearch338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/search_32.png"))); // NOI18N
        lbSearch338.setText("Tìm kiếm: ");
        lbSearch338.setToolTipText("");

        txtSearch338.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearch338.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearch338KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelNorth338Layout = new javax.swing.GroupLayout(PanelNorth338);
        PanelNorth338.setLayout(PanelNorth338Layout);
        PanelNorth338Layout.setHorizontalGroup(
            PanelNorth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNorth338Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNorth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelNorth338Layout.createSequentialGroup()
                        .addComponent(lbPosition338, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPosition338, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275)
                        .addComponent(lbSearch338)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch338, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNorth338Layout.setVerticalGroup(
            PanelNorth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNorth338Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(PanelNorth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPosition338)
                    .addComponent(lbSearch338)
                    .addComponent(cbbPosition338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelSouth338.setBackground(new java.awt.Color(69, 32, 16));

        btnAddAcc338.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAcc338.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddAcc338.setForeground(new java.awt.Color(51, 0, 51));
        btnAddAcc338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/file_add.png"))); // NOI18N
        btnAddAcc338.setText("THÊM");
        btnAddAcc338.setToolTipText("");
        btnAddAcc338.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAddAcc338.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddAcc338.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAcc338ActionPerformed(evt);
            }
        });

        btnEditAcc338.setBackground(new java.awt.Color(255, 255, 255));
        btnEditAcc338.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditAcc338.setForeground(new java.awt.Color(51, 0, 51));
        btnEditAcc338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/document_edit.png"))); // NOI18N
        btnEditAcc338.setText("SỬA");
        btnEditAcc338.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEditAcc338.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditAcc338.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAcc338ActionPerformed(evt);
            }
        });

        btnDeleteAcc338.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAcc338.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteAcc338.setForeground(new java.awt.Color(51, 0, 51));
        btnDeleteAcc338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/file_delete.png"))); // NOI18N
        btnDeleteAcc338.setText("XÓA");
        btnDeleteAcc338.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDeleteAcc338.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteAcc338.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAcc338ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/logo_130.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("VNI-Park", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YMach Cafe");
        jLabel5.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cup_2_110.png"))); // NOI18N

        PanelSouth339.setBackground(new java.awt.Color(69, 32, 16));
        PanelSouth339.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAcc339.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAcc339.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddAcc339.setForeground(new java.awt.Color(51, 0, 51));
        btnAddAcc339.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/file_add.png"))); // NOI18N
        btnAddAcc339.setText("THÊM");
        btnAddAcc339.setToolTipText("");
        btnAddAcc339.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAddAcc339.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddAcc339.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAcc339ActionPerformed(evt);
            }
        });
        PanelSouth339.add(btnAddAcc339, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 1, 104, -1));

        btnEditAcc339.setBackground(new java.awt.Color(255, 255, 255));
        btnEditAcc339.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditAcc339.setForeground(new java.awt.Color(51, 0, 51));
        btnEditAcc339.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/document_edit.png"))); // NOI18N
        btnEditAcc339.setText("SỬA");
        btnEditAcc339.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEditAcc339.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditAcc339.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAcc339ActionPerformed(evt);
            }
        });
        PanelSouth339.add(btnEditAcc339, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 0, 104, 41));

        btnDeleteAcc339.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAcc339.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteAcc339.setForeground(new java.awt.Color(51, 0, 51));
        btnDeleteAcc339.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/file_delete.png"))); // NOI18N
        btnDeleteAcc339.setText("XÓA");
        btnDeleteAcc339.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDeleteAcc339.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteAcc339.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAcc339ActionPerformed(evt);
            }
        });
        PanelSouth339.add(btnDeleteAcc339, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 0, 104, 41));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 70, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel26.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel26.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 70, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 70, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/logo_130.png"))); // NOI18N
        PanelSouth339.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, 137));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cup_2_110.png"))); // NOI18N
        PanelSouth339.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 71, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel30.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel30.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 70, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 70, 50));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel32.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel32.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 70, 50));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 70, 50));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel34.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel34.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 70, 50));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 70, 50));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel36.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel36.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 70, 50));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 70, 50));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel38.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel38.setMinimumSize(new java.awt.Dimension(80, 70));
        PanelSouth339.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 70, 50));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        PanelSouth339.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 70, 50));

        jLabel4.setBackground(new java.awt.Color(69, 32, 16));
        jLabel4.setFont(new java.awt.Font("VNI-Park", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("YMach Cafe");
        jLabel4.setToolTipText("");
        PanelSouth339.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N
        jLabel28.setMaximumSize(new java.awt.Dimension(80, 70));
        jLabel28.setMinimumSize(new java.awt.Dimension(80, 70));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_mangement/image/cf_cup.png"))); // NOI18N

        javax.swing.GroupLayout PanelSouth338Layout = new javax.swing.GroupLayout(PanelSouth338);
        PanelSouth338.setLayout(PanelSouth338Layout);
        PanelSouth338Layout.setHorizontalGroup(
            PanelSouth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSouth338Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(PanelSouth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAcc338, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSouth338Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(PanelSouth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelSouth338Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnEditAcc338, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btnDeleteAcc338, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2))
            .addGroup(PanelSouth338Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addComponent(PanelSouth339, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelSouth338Layout.setVerticalGroup(
            PanelSouth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSouth338Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btnAddAcc338)
                .addGroup(PanelSouth338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel5))
            .addComponent(btnEditAcc338, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDeleteAcc338, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelSouth338Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2))
            .addGroup(PanelSouth338Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(PanelSouth339, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelCenter338.setBackground(new java.awt.Color(69, 32, 16));

        tbDish338.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbDish338.setForeground(new java.awt.Color(51, 0, 51));
        tbDish338.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDish338.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDish338MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDish338);

        javax.swing.GroupLayout PanelCenter338Layout = new javax.swing.GroupLayout(PanelCenter338);
        PanelCenter338.setLayout(PanelCenter338Layout);
        PanelCenter338Layout.setHorizontalGroup(
            PanelCenter338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
            .addGroup(PanelCenter338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE))
        );
        PanelCenter338Layout.setVerticalGroup(
            PanelCenter338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(PanelCenter338Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCenter338Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCenter338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelSouth338, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelNorth338, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelNorth338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelCenter338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelSouth338, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbPosition338ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPosition338ItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPosition338ItemStateChanged

    private void cbbPosition338ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPosition338ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPosition338ActionPerformed

    private void txtSearch338KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch338KeyReleased

    }//GEN-LAST:event_txtSearch338KeyReleased

    private void tbDish338MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDish338MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDish338MouseClicked

    private void btnAddAcc338ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAcc338ActionPerformed

    }//GEN-LAST:event_btnAddAcc338ActionPerformed

    private void btnEditAcc338ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAcc338ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAcc338ActionPerformed

    private void btnDeleteAcc338ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAcc338ActionPerformed

    }//GEN-LAST:event_btnDeleteAcc338ActionPerformed

    private void btnAddAcc339ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAcc339ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAcc339ActionPerformed

    private void btnEditAcc339ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAcc339ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAcc339ActionPerformed

    private void btnDeleteAcc339ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAcc339ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAcc339ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_Managerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_Managerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_Managerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_Managerment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_Managerment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCenter338;
    private javax.swing.JPanel PanelNorth338;
    private javax.swing.JPanel PanelSouth338;
    private javax.swing.JPanel PanelSouth339;
    private javax.swing.JButton btnAddAcc338;
    private javax.swing.JButton btnAddAcc339;
    private javax.swing.JButton btnDeleteAcc338;
    private javax.swing.JButton btnDeleteAcc339;
    private javax.swing.JButton btnEditAcc338;
    private javax.swing.JButton btnEditAcc339;
    private javax.swing.JComboBox<String> cbbPosition338;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPosition338;
    private javax.swing.JLabel lbSearch338;
    private javax.swing.JTable tbDish338;
    private javax.swing.JTextField txtSearch338;
    // End of variables declaration//GEN-END:variables
}
