/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.java.coffee_mangement.view;

/**
 *
 * @author ASUS
 */
public class Statics_General extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public Statics_General() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnQLNV234 = new javax.swing.JButton();
        btnQLTD234 = new javax.swing.JButton();
        btnQLB234 = new javax.swing.JButton();
        btnQLTK234 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(1038, 486));

        jPanel3.setBackground(new java.awt.Color(69, 32, 16));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnQLNV234.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNV234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLNV234.setForeground(new java.awt.Color(51, 51, 0));
        btnQLNV234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_management/view/icon/employment.png"))); // NOI18N
        btnQLNV234.setText("THỐNG KÊ THEO MÓN");
        btnQLNV234.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNV234.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLNV234.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLNV234.setIconTextGap(10);
        btnQLNV234.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLNV234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNV234ActionPerformed(evt);
            }
        });

        btnQLTD234.setBackground(new java.awt.Color(255, 255, 255));
        btnQLTD234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLTD234.setForeground(new java.awt.Color(51, 51, 0));
        btnQLTD234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_management/view/icon/menu.png"))); // NOI18N
        btnQLTD234.setText("THỐNG KÊ THEO NGÀY ");
        btnQLTD234.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTD234.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLTD234.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTD234.setIconTextGap(10);
        btnQLTD234.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLTD234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTD234ActionPerformed(evt);
            }
        });

        btnQLB234.setBackground(new java.awt.Color(255, 255, 255));
        btnQLB234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLB234.setForeground(new java.awt.Color(51, 51, 0));
        btnQLB234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_management/view/icon/table.png"))); // NOI18N
        btnQLB234.setText("QUẢN LÝ BÀN");
        btnQLB234.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLB234.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLB234.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLB234.setIconTextGap(10);
        btnQLB234.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLB234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLB234ActionPerformed(evt);
            }
        });

        btnQLTK234.setBackground(new java.awt.Color(255, 255, 255));
        btnQLTK234.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLTK234.setForeground(new java.awt.Color(51, 51, 0));
        btnQLTK234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_management/view/icon/profile-user.png"))); // NOI18N
        btnQLTK234.setText("QUẢN LÝ TÀI KHOẢN");
        btnQLTK234.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTK234.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLTK234.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTK234.setIconTextGap(10);
        btnQLTK234.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLTK234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTK234ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQLTD234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLNV234, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btnQLB234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLTK234, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLTD234, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLNV234, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLB234, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLTK234, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 733, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNV234ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNV234ActionPerformed
        LoadPanel(3);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLNV234ActionPerformed

    private void btnQLTD234ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTD234ActionPerformed
        LoadPanel(2);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLTD234ActionPerformed

    private void btnQLB234ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLB234ActionPerformed
        LoadPanel(1);                // TODO add your handling code here:
    }//GEN-LAST:event_btnQLB234ActionPerformed

    private void btnQLTK234ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTK234ActionPerformed
        LoadPanel(4);  // TODO add your handling code here:
    }//GEN-LAST:event_btnQLTK234ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statics_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statics_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statics_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statics_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Statics_General().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLB234;
    private javax.swing.JButton btnQLNV234;
    private javax.swing.JButton btnQLTD234;
    private javax.swing.JButton btnQLTK234;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void LoadPanel(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
